name: ${project.artifactId}
version: ${project.version}
main: ${plugin.main}
depend: [CivModCore]
softdepend: [Citadel, NameLayer]
api-version: ${minecraft.version}
authors: [Okx, Protonull]
description: Easily make rail switches for automated destination selection
commands:
  dest: {}